#!/bin/bash
# Sourced by the shell-based tests. Gives each run a throwaway XDG home and the
# fake tools in $PATH.
#
# Two reasons the sandbox is per-run and not per-suite, both learned the hard
# way: a reused XDG_DATA_HOME keeps the docks the previous run created (so the
# next one starts at another slot and assertions fail for an unrelated reason),
# and Translations::seedFiles() only copies files that are *missing*, so a stale
# translations/ directory hides catalogue changes and looks like a code bug.

# kdock_sandbox <name> -> exports KDOCK_SANDBOX, XDG_DATA_HOME, XDG_CONFIG_HOME,
# XDG_CACHE_HOME and prepends the fake tools to PATH. Registers cleanup on exit.
kdock_sandbox() {
    local name=${1:-kdock-test}
    KDOCK_SANDBOX=$(mktemp -d "/tmp/${name}.XXXXXX")
    export KDOCK_SANDBOX
    export XDG_DATA_HOME="$KDOCK_SANDBOX/data"
    export XDG_CONFIG_HOME="$KDOCK_SANDBOX/config"
    export XDG_CACHE_HOME="$KDOCK_SANDBOX/cache"
    mkdir -p "$XDG_DATA_HOME/kdock" "$XDG_CONFIG_HOME" "$XDG_CACHE_HOME"

    # The fake tools: generated by the build (KDOCK_FAKEBIN) or on the spot when
    # a script is run by hand.
    if [ -z "${KDOCK_FAKEBIN:-}" ] || [ ! -x "$KDOCK_FAKEBIN/pactl" ]; then
        KDOCK_FAKEBIN="$KDOCK_SANDBOX/fakebin"
        "$(dirname "${BASH_SOURCE[0]}")/fakebin.sh" "$KDOCK_FAKEBIN"
    fi
    export KDOCK_FAKEBIN
    export PATH="$KDOCK_FAKEBIN:$PATH"

    kdock_on_exit kdock_sandbox_cleanup
}

# Pila de limpiezas. Un `trap ... EXIT` pelado en cada helper se PISA con el del
# script que lo llama —el primero que se registra deja de correr— y el síntoma es
# feo: procesos de prueba vivos y un .desktop temporal que le sigue concediendo
# privilegios de KWin a lo que haya en esa ruta. Todo lo que tenga que limpiar se
# registra por acá.
KDOCK_EXIT_HOOKS=()
kdock_on_exit() {
    KDOCK_EXIT_HOOKS+=("$1")
    # shellcheck disable=SC2064
    trap 'kdock_run_exit_hooks' EXIT
}

kdock_run_exit_hooks() {
    local i
    for (( i=${#KDOCK_EXIT_HOOKS[@]}-1 ; i>=0 ; i-- )); do
        "${KDOCK_EXIT_HOOKS[i]}" || true
    done
    KDOCK_EXIT_HOOKS=()
}

kdock_sandbox_cleanup() {
    [ -n "${KDOCK_SANDBOX:-}" ] && [ -d "$KDOCK_SANDBOX" ] && rm -rf "$KDOCK_SANDBOX"
    return 0
}

# Link the user's real .desktop / icon trees into the sandbox. Needed by anything
# that resolves launchers (the dock's app icons, the tile menu): with an isolated
# XDG_DATA_HOME and nothing in it, menus come up **empty and look like a bug**.
# Read-only symlinks, so the sandbox still absorbs every write.
kdock_sandbox_link_apps() {
    local src
    for src in applications desktop-directories icons; do
        if [ -d "$HOME/.local/share/$src" ]; then
            ln -sfn "$HOME/.local/share/$src" "$XDG_DATA_HOME/$src"
        fi
    done
}

# Point the sandbox at the committed fixture apps instead of the user's, so the
# result does not depend on what happens to be installed (this is what CI uses).
kdock_sandbox_fixture_apps() {
    local fixtures=${1:?usage: kdock_sandbox_fixture_apps <fixtures-dir>}
    ln -sfn "$fixtures/applications" "$XDG_DATA_HOME/applications"
}

kdock_skip() { echo "SKIP: $*" >&2; exit 77; }
kdock_fail() { echo "FAIL: $*" >&2; exit 1; }
kdock_info() { echo "  $*"; }
